# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Bit-level parity test: MLX depthformer vs JAX reference (fp32).

Compares MLX temporal_inputs, temporal_outputs, and depth_logits against
golden JAX reference values generated in float32. Both backends use the
same checkpoint weights and conditioning inputs.

For the depth decoder, we use "teacher forcing": at each RVQ iteration,
we feed the token that JAX sampled (from the reference data) into the
MLX depth decoder, so that the depth decoder inputs are identical and
the logits can be compared deterministically across all 16 iterations.

Only the first streaming step is tested because subsequent steps depend
on stochastically sampled tokens (temperature + top-k), so different
random number generators (JAX vs MLX) produce different `previous_frame`
tokens at step 2+.

Reference data was generated by:
  scripts/generate_test_reference.py  (JAX, compute_dtype=float32)

To regenerate reference data:
  python scripts/generate_test_reference.py

Usage:
  pytest tests/test_bitlevel_parity.py
"""

# CI checkpoint: mrt2_small.safetensors (downloaded by the CI workflow).
# Reference data must be regenerated when switching models:
#   python scripts/generate_test_reference.py --model=mrt2_small

import unittest
from pathlib import Path

import mlx.core as mx
import numpy as np
import numpy.testing as npt

import magenta_rt  # noqa: F401 — activates vendored sequence_layers
import sequence_layers.mlx as sl
from magenta_rt.mlx import model
from magenta_rt.mlx import system
from magenta_rt.mlx import spectrostream
from magenta_rt.mlx import load_weights as lw
from magenta_rt.mlx import depthformer
from magenta_rt import paths

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
_TESTDATA_DIR = Path(__file__).parent / 'testdata'
_CI_CHECKPOINT_NAME = 'mrt2_small.safetensors'
_CHECKPOINT = paths.resolve_checkpoint(_CI_CHECKPOINT_NAME)

# Conditioning tokens (must match jax/generate_test_reference.py).
_MUSICCOCA = [660, 1016, 295, 206, 857, 841, 391, 857, 619, 70, 401, 22]
_NOTES = [0] * 127 + [1]
_DRUMS = [-1]
_CFG_CONDITIONING = [4, 4, 4]
NUM_RESERVED_TOKENS = 7  # system.NUM_RESERVED_TOKENS(6) + 1 dropout

# Tolerance: max abs diff < 1e-4 for float32 parity.
# Measured: temporal max ~3e-5, depth logits max ~6.3e-5 (at rvq=2+).
# Errors accumulate across the 16 autoregressive depth decoder steps.
_ATOL = 1e-3


def _build_model_and_constants():
    """Build MLX model in float32 and return (system, constants, block)."""
    exp = model.MagentaRT2ModelSmall()
    exp.compute_dtype = mx.float32  # fp32 for parity testing
    rvq_truncation = exp.spectrostream.rvq_truncation_level
    depthformer_config = exp.depthformer_config()
    spectrostream_config = spectrostream.stft_spectrostream_40ms_generic_48khz_stereo_config(
        rvq_truncation_level=rvq_truncation, use_unique_codes=False,
    )
    mrt_config = system.MagentaRT2Sampler.Config(
        depthformer=depthformer_config, spectrostream=spectrostream_config,
    )
    mrt_sampler = mrt_config.make()

    # Skip bf16 conversion — keep params in float32 for parity.
    original_convert = lw.convert_to_bf16
    lw.convert_to_bf16 = lambda module: None
    lw.load_weights(
        mrt_sampler, _CHECKPOINT, num_input_channels=exp.input_num_channels
    )
    lw.convert_to_bf16 = original_convert

    # Conditioning inputs.
    cond_tokens = np.concatenate([_MUSICCOCA, _NOTES, _DRUMS, _CFG_CONDITIONING], axis=0) + NUM_RESERVED_TOKENS
    block = sl.Sequence(
        mx.array(cond_tokens.reshape(1, 1, -1), dtype=mx.int32),
        mx.array([[True]], dtype=mx.bool_),
    )
    constants = {
        'temperature': mx.array([1.3]),
        'top_k': mx.array([40]),
    }
    return mrt_sampler, constants, block


def _run_temporal_step(mrt_sampler, constants, block):
    """Run one streaming step, capture temporal_inputs and temporal_outputs.

    Returns (temporal_inputs, temporal_outputs, temporal_state, decoder).
    These are NumPy arrays (already evaluated) plus MLX state for the depth test.
    """
    input_spec = sl.ChannelSpec(shape=[len(_MUSICCOCA) + len(_NOTES) + len(_DRUMS) + len(_CFG_CONDITIONING)], dtype=mx.int32)
    state = mrt_sampler.get_initial_state(1, input_spec, constants=constants)

    decoder = mrt_sampler.depthformer.decoder

    # Unpack system state to get decoder state.
    # system.step_with_emits -> depthformer.step_with_emits -> encoder + decoder
    # We need to go through the encoder first, then run the decoder manually.
    # Instead, let's monkey-patch to capture everything.

    captured = {}
    original_step = depthformer.MultivariateDecoder.step_with_emits

    def _patched_step(self, x, state_inner, *, training=False, constants=None):
        rng, previous_frame, temporal_state, step = state_inner
        constants = constants or {}
        batch_size, _, _ = previous_frame.shape

        # Temporal path.
        embedded_frame = self.embedder.layer(previous_frame)
        temporal_inputs = embedded_frame.apply_values(
            depthformer._mean_in_f32, axis=-2
        )
        temporal_outputs, new_temporal_state = self.temporal_body.step(
            temporal_inputs, temporal_state, training=training, constants=constants,
        )
        mx.eval(temporal_inputs.values, temporal_outputs.values)

        captured['temporal_inputs'] = np.array(temporal_inputs.values)
        captured['temporal_outputs'] = np.array(temporal_outputs.values)
        captured['temporal_outputs_seq'] = temporal_outputs
        captured['decoder'] = self
        captured['batch_size'] = batch_size
        captured['training'] = training

        return original_step(self, x, state_inner, training=training, constants=constants)

    depthformer.MultivariateDecoder.step_with_emits = _patched_step
    try:
        _, _, _ = mrt_sampler.step_with_emits(x=block, state=state, constants=constants)
    finally:
        depthformer.MultivariateDecoder.step_with_emits = original_step

    return captured


def _run_depth_teacher_forced(decoder, temporal_outputs_seq, jax_depth_samples, training=False):
    """Run the depth decoder with teacher forcing using JAX's sampled tokens.

    At each RVQ iteration, instead of sampling from logits, we feed the
    token that JAX sampled. This makes the depth decoder path deterministic
    and allows comparing logits at every iteration.

    Args:
        decoder: The MLX MultivariateDecoder.
        temporal_outputs_seq: sl.Sequence with temporal_outputs (depth input at rvq=0).
        jax_depth_samples: np.array of shape [num_rvq, batch, 1] with JAX's sampled tokens.
        training: Whether to run in training mode.

    Returns:
        List of np.arrays, one per RVQ iteration, containing the raw logits
        (before soft_cap) of shape [batch, 1, vocab].
    """
    batch_size = temporal_outputs_seq.shape[0]
    depth_state = decoder.depth_body.get_initial_state(
        batch_size=batch_size,
        input_spec=temporal_outputs_seq.channel_spec,
        training=training,
    )

    depth_inputs = temporal_outputs_seq
    num_rvq = jax_depth_samples.shape[0]
    all_logits = []

    for rvq_index in range(num_rvq):
        logits, depth_state = decoder.depth_body.step(
            depth_inputs, depth_state, training=training,
        )
        mx.eval(logits.values)
        all_logits.append(np.array(logits.values))

        # Teacher forcing: use JAX's sampled token as input for the next step.
        # jax_depth_samples[rvq_index] is shape [batch, time] = [4, 1].
        jax_token = mx.array(jax_depth_samples[rvq_index])  # [batch, 1]
        mask = mx.ones(jax_token.shape[:2], dtype=mx.bool_)  # [batch, 1]
        depth_sample = sl.Sequence(jax_token, mask)
        depth_inputs = decoder.embedder.layer(depth_sample)

    return all_logits


@unittest.skipUnless(
    _CHECKPOINT.exists(),
    f'Checkpoint not found: {_CHECKPOINT}',
)
@unittest.skipUnless(
    (_TESTDATA_DIR / 'jax_fp32_step1_temporal_inputs.npy').exists(),
    f'Reference data not found in {_TESTDATA_DIR}. '
    f'Run jax/generate_test_reference.py first.',
)
class TestBitlevelParity(unittest.TestCase):
    """Compare MLX fp32 intermediates against JAX fp32 golden references."""

    @classmethod
    def setUpClass(cls):
        """Build the model once and run temporal + depth steps."""
        print('Building MLX model (compute_dtype=float32)...')
        cls.mrt_sampler, cls.constants, cls.block = _build_model_and_constants()

        print('Running temporal step...')
        cls.captured = _run_temporal_step(
            cls.mrt_sampler, cls.constants, cls.block
        )

        print('Running depth decoder (teacher-forced)...')
        jax_depth_samples = np.load(
            _TESTDATA_DIR / 'jax_fp32_step1_depth_samples.npy'
        )
        cls.depth_logits = _run_depth_teacher_forced(
            cls.captured['decoder'],
            cls.captured['temporal_outputs_seq'],
            jax_depth_samples,
            training=cls.captured['training'],
        )
        print('Setup complete.')

    # ------------------------------------------------------------------
    # Temporal body
    # ------------------------------------------------------------------
    def test_temporal_inputs(self):
        """temporal_inputs should match JAX reference within fp32 ULP."""
        ref = np.load(_TESTDATA_DIR / 'jax_fp32_step1_temporal_inputs.npy')
        mlx_val = self.captured['temporal_inputs']
        npt.assert_allclose(
            mlx_val, ref, atol=_ATOL, rtol=0,
            err_msg='temporal_inputs diverged from JAX reference.',
        )
        max_diff = np.max(np.abs(mlx_val - ref))
        print(f'  temporal_inputs  max_diff={max_diff:.2e}  ✓')

    def test_temporal_outputs(self):
        """temporal_outputs should match JAX reference within fp32 ULP."""
        ref = np.load(_TESTDATA_DIR / 'jax_fp32_step1_temporal_outputs.npy')
        mlx_val = self.captured['temporal_outputs']
        npt.assert_allclose(
            mlx_val, ref, atol=_ATOL, rtol=0,
            err_msg='temporal_outputs diverged from JAX reference.',
        )
        max_diff = np.max(np.abs(mlx_val - ref))
        print(f'  temporal_outputs max_diff={max_diff:.2e}  ✓')

    # ------------------------------------------------------------------
    # Depth decoder (teacher-forced, all 16 RVQ iterations)
    # ------------------------------------------------------------------
    def test_depth_logits_all_rvq(self):
        """Depth logits should match JAX at every RVQ index (teacher forced)."""
        ref_all = np.load(_TESTDATA_DIR / 'jax_fp32_step1_depth_logits.npy')
        num_rvq = ref_all.shape[0]

        max_diffs = []
        for rvq_idx in range(num_rvq):
            ref = ref_all[rvq_idx]
            mlx_val = self.depth_logits[rvq_idx]
            diff = np.max(np.abs(mlx_val - ref))
            max_diffs.append(diff)
            npt.assert_allclose(
                mlx_val, ref, atol=_ATOL, rtol=0,
                err_msg=f'depth_logits diverged at rvq={rvq_idx} '
                        f'(max_diff={diff:.2e}).',
            )

        overall_max = max(max_diffs)
        print(f'  depth_logits     max_diff={overall_max:.2e} '
              f'(across {num_rvq} RVQ levels)  ✓')
        for i, d in enumerate(max_diffs):
            status = '✓' if d < _ATOL else '✗'
            print(f'    rvq={i:2d}: max_diff={d:.2e}  {status}')


if __name__ == '__main__':
    unittest.main(verbosity=2)
